/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

import java.awt.Frame;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;

/**
 *
 * @author ilhamrigan
 */
public class SPK extends javax.swing.JFrame {

    lihatNormalisasi norm = new lihatNormalisasi(this, true);
    Object[] header1 = {"ALTERNATIF", "JARAK", "KEPADATAN", "HARGA", "AKSESIBILITAS", "LUAS"};
    Object[][] data1 = null;
    DefaultTableModel model1 = new DefaultTableModel(data1, header1);

    /**
     * Creates new form SPK
     */
    public SPK() {
        initComponents();

        setLocationRelativeTo(null);
        loadKriteria();
        loadAlternatif();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        
        btnNorm.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKriteria = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        editSuplemen = new javax.swing.JButton();
        btnHapusAlt = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAlternatif = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        perhitungan = new javax.swing.JButton();
        btnNorm = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        hasilPembobotan = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        nilaiQ = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(54, 81, 126));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PEMILIHAN TEMPAT USAHA TERBAIK DI TEGAL MENGGUNAKAN METODE SAW");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(54, 81, 126));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 964, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.setBackground(new java.awt.Color(54, 81, 126));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setBackground(new java.awt.Color(54, 81, 126));
        jPanel6.setPreferredSize(new java.awt.Dimension(873, 50));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(54, 81, 126));
        jButton1.setText("Edit Kriteria");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jButton1)
                .addContainerGap(828, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.add(jPanel6, java.awt.BorderLayout.PAGE_START);

        tblKriteria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblKriteria);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Kriteria", jPanel3);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(54, 81, 126));
        jPanel7.setPreferredSize(new java.awt.Dimension(873, 50));

        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(54, 81, 126));
        jButton3.setText("Tambah ");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        editSuplemen.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        editSuplemen.setForeground(new java.awt.Color(54, 81, 126));
        editSuplemen.setText("Edit");
        editSuplemen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSuplemenActionPerformed(evt);
            }
        });

        btnHapusAlt.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnHapusAlt.setForeground(new java.awt.Color(54, 81, 126));
        btnHapusAlt.setText("Hapus");
        btnHapusAlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusAltActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        txtCari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtCariKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editSuplemen, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHapusAlt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 421, Short.MAX_VALUE)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCari)
                    .addComponent(btnHapusAlt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editSuplemen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(jPanel7, java.awt.BorderLayout.PAGE_START);

        tblAlternatif.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblAlternatif);

        jPanel4.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        jTabbedPane1.addTab("Alternatif", jPanel4);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel8.setBackground(new java.awt.Color(54, 81, 126));
        jPanel8.setPreferredSize(new java.awt.Dimension(873, 50));

        perhitungan.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        perhitungan.setForeground(new java.awt.Color(54, 81, 126));
        perhitungan.setText("Lakukan Perhitungan");
        perhitungan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perhitunganActionPerformed(evt);
            }
        });

        btnNorm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnNorm.setForeground(new java.awt.Color(54, 81, 126));
        btnNorm.setText("Lihat Normalisasi");
        btnNorm.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                btnNormAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        btnNorm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNormActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(perhitungan)
                .addGap(18, 18, 18)
                .addComponent(btnNorm, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnNorm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(perhitungan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.add(jPanel8, java.awt.BorderLayout.PAGE_START);

        hasilPembobotan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(hasilPembobotan);

        jPanel5.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        jPanel9.setPreferredSize(new java.awt.Dimension(873, 50));

        nilaiQ.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nilaiQ.setForeground(new java.awt.Color(54, 81, 126));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(nilaiQ, javax.swing.GroupLayout.DEFAULT_SIZE, 936, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(nilaiQ, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.add(jPanel9, java.awt.BorderLayout.PAGE_END);

        jTabbedPane1.addTab("Pembobotan", jPanel5);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin Untuk Keluar dari SPK Pemilihan Tempat Usaha terbaik di Kota Tegal?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (konfirmasi == JOptionPane.YES_OPTION) {
            setDefaultCloseOperation(EXIT_ON_CLOSE);
        } else {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnNormActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNormActionPerformed
        // TODO add your handling code here:

        norm.setVisible(true);
    }//GEN-LAST:event_btnNormActionPerformed

    private void btnNormAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_btnNormAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNormAncestorAdded

    private void perhitunganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perhitunganActionPerformed
        // TODO add your handling code here:
        SPK_SAW();
    }//GEN-LAST:event_perhitunganActionPerformed

    private void txtCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariKeyPressed
        // TODO add your handling code here:
        String key = txtCari.getText();
        cariData(key);
    }//GEN-LAST:event_txtCariKeyPressed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnHapusAltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusAltActionPerformed
        // TODO add your handling code here:
        int barisDel = tblAlternatif.getSelectedRow();
        hapusAlt(barisDel);

    }//GEN-LAST:event_btnHapusAltActionPerformed

    private void editSuplemenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSuplemenActionPerformed
        // TODO add your handling code here:
        int baris = tblAlternatif.getSelectedRow();
        ShowEdit(baris);
    }//GEN-LAST:event_editSuplemenActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        tambahTempat tbhS = new tambahTempat();
        tbhS.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int baris = tblKriteria.getSelectedRow();
        ShowEditKriteria(baris);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SPK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SPK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapusAlt;
    public static javax.swing.JButton btnNorm;
    private javax.swing.JButton editSuplemen;
    private javax.swing.JTable hasilPembobotan;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel nilaiQ;
    private javax.swing.JButton perhitungan;
    public static javax.swing.JTable tblAlternatif;
    public static javax.swing.JTable tblKriteria;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables

    public static void loadKriteria() {
        Object[][] data = null;
        Object[] header = {"ID", "KRITERIA", "BOBOT", "LABEL", "KODE"};
        DefaultTableModel model = new DefaultTableModel(data, header);
        tblKriteria.setModel(model);
        int nomor = 0;
        
        String query = "SELECT * FROM kriteria";
        
        try (Connection koneksi = Koneksi.konekKeDB();
             Statement st = koneksi.createStatement();
             ResultSet rs = st.executeQuery(query)) {

            while (rs.next()) {
                int id = rs.getInt("id_kriteria");
                String nama = rs.getString("nama");
                String bobot = rs.getString("bobot");
                String label = rs.getString("label");
                String kode = rs.getString("kode");
                nomor++;
                Object[] d = {nomor, nama, bobot, label, kode};
                model.addRow(d);
            }
        } catch (SQLException e) {
            e.printStackTrace();  // Enhanced error handling
        }
    }

    public static void loadAlternatif() {
        Object[][] data = null;
        Object[] header = {"ID", "NAMA", "JARAK", "KEPADATAN", "HARGA", "AKSESIBILITAS", "LUAS", "DESKRIPSI"};
        DefaultTableModel model = new DefaultTableModel(data, header); 
        tblAlternatif.setModel(model);

        int nomor = 0;
        try {
            Connection koneksi = Koneksi.konekKeDB();
            Statement st = koneksi.createStatement();
            String query = "SELECT * FROM tempat_usaha";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama_tempat");
                double jarak = rs.getDouble("jarak");
                double kepadatan = rs.getDouble("kepadatan");
                double harga = rs.getDouble("harga");
                double aksesibilitas = rs.getDouble("aksesibilitas");
                double luas = rs.getDouble("luas");
                String deskripsi = rs.getString("info");

                nomor++;
                Object[] d = {nomor, nama, jarak, kepadatan, harga, aksesibilitas, luas, deskripsi};
                model.addRow(d);
            }
            koneksi.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    private void SPK_SAW() {
        try {
            int nomor = 0;
            TruncateTbl("pemilihan");
            model1.getDataVector().removeAllElements();

            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT * FROM tempat_usaha";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                double jarak = rs.getDouble("jarak");
                double kepadatan = rs.getDouble("kepadatan");
                double harga = rs.getDouble("harga");
                double aksesibilitas = rs.getDouble("aksesibilitas");
                double luas = rs.getDouble("luas");

                double pembagi_jarak = label("jarak").equals("cost") ? min("jarak") : max("jarak");
                double pembagi_kepadatan = label("kepadatan").equals("cost") ? min("kepadatan") : max("kepadatan");
                double pembagi_harga = label("harga").equals("cost") ? min("harga") : max("harga");
                double pembagi_aksesibilitas = label("aksesibilitas").equals("cost") ? min("aksesibilitas") : max("aksesibilitas");
                double pembagi_luas = label("luas").equals("cost") ? min("luas") : max("luas");

                double norm_jarak = label("jarak").equals("cost") ? min("jarak") / jarak : jarak / max("jarak");
                double norm_kepadatan = label("kepadatan").equals("cost") ? min("kepadatan") / kepadatan : kepadatan / max("kepadatan");
                double norm_harga = label("harga").equals("cost") ? min("harga") / harga : harga / max("harga");
                double norm_aksesibilitas = label("aksesibilitas").equals("cost") ? min("aksesibilitas") / aksesibilitas : aksesibilitas / max("aksesibilitas");
                double norm_luas = label("luas").equals("cost") ? min("luas") / luas : luas / max("luas");

                double hasil = (bobot("jarak") * norm_jarak) + (bobot("kepadatan") * norm_kepadatan) + (bobot("harga") * norm_harga) + (bobot("aksesibilitas") * norm_aksesibilitas) + (bobot("luas") * norm_luas);
                nomor++;

                String nama_alt = rs.getString("nama_tempat");
                DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyy/MM/dd HH:mm:ss");
                LocalDateTime now = LocalDateTime.now();

                Connection c2 = Koneksi.konekKeDB();
                Statement st2 = c2.createStatement();
                String queryNorm = "INSERT INTO pemilihan VALUES(NULL, '" + nama_alt + "', '" + dtf.format(now) + "', " + hasil + ");";
                st2.executeUpdate(queryNorm);
                c2.close();

                hasilSPK();

                Object[] dataq = {nama_alt, norm_jarak, norm_kepadatan, norm_harga, norm_aksesibilitas, norm_luas};
                norm.tblNormalisasi.setModel(model1);
                model1.addRow(dataq);
            }
            c.close();

            nilaiQ.setText("Hasil Pemilihan tempat usaha terbaik adalah di: " + hasilPembobotan.getValueAt(0, 1) + " dengan nilai: " + hasilPembobotan.getValueAt(0, 2));
        } catch (SQLException e) {
            e.printStackTrace();
        }

        btnNorm.setEnabled(true);
    }

    private double min(String kolom) {
        double min = 0;
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT MIN(" + kolom + ") AS min_kolom FROM tempat_usaha";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                min = rs.getDouble("min_kolom");
            }
            c.close();
            return min;

        } catch (SQLException e) {
        }
        return min;
    }

    private double max(String kolom) {
        double max = 0;
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT MAX(" + kolom + ") AS max_kolom FROM tempat_usaha";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                max = rs.getDouble("max_kolom");
            }
            c.close();
            return max;

        } catch (SQLException e) {
        }
        return max;
    }

    private String label(String kolom) {
        String label = "cost";
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT label FROM kriteria WHERE nama='" + kolom + "'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                label = rs.getString("label");
            }
            c.close();
            return label;

        } catch (SQLException e) {
        }
        return label;
    }

    private double bobot(String kolom) {
        double bobot = 0;
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String query = "SELECT bobot FROM kriteria WHERE nama='" + kolom + "'";
            ResultSet rs = st.executeQuery(query);
            while (rs.next()) {
                bobot = rs.getDouble("bobot");
            }
            c.close();
            return bobot;

        } catch (SQLException e) {
        }
        return bobot;
    }

    private void cariData(String key) {
        Object[] header = {"ID", "NAMA", "JARAK", "KEPADATAN", "HARGA", "LUAS", "AKSESIBILITAS", "DESKRIPSI"};
        Object[][] data = null;

        DefaultTableModel model = new DefaultTableModel(data, header);
        tblAlternatif.setModel(model);

        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            model.getDataVector().removeAllElements();
            String sql = "SELECT * FROM tempat_usaha WHERE nama_tempat LIKE '%" + key + "%'";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama_tempat");
                double jarak = rs.getDouble("jarak");
                double kepadatan = rs.getDouble("kepadatan");
                double harga = rs.getDouble("harga");
                double aksesibilitas = rs.getDouble("aksesibilitas");
                double luas = rs.getDouble("luas");
                String deskripsi = rs.getString("info");

                Object[] d = {id, nama, jarak, kepadatan, harga, aksesibilitas, luas, deskripsi};
                model.addRow(d);
            }
            c.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    private void ShowEditKriteria(int baris) {
        if (baris >= 0) {
            editKriteria edtKri = new editKriteria(this, true);
            
            int idK = (int) tblKriteria.getValueAt(baris, 0);
            edtKri.noKriteria = idK;

            String namaKri = (String) tblKriteria.getValueAt(baris, 1);
            edtKri.txtKriteria.setText(namaKri);

            String bobot = (String) tblKriteria.getValueAt(baris, 2);
            edtKri.txtBobot.setText(bobot);

            String label = (String) tblKriteria.getValueAt(baris, 3);
            edtKri.txtLabel.setText(label);

            edtKri.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu");
        }
    }

    private void ShowEdit(int baris) {
        if (baris >= 0) {
            updateTempat updTem = new updateTempat(this, true);

            String nama = String.valueOf(tblAlternatif.getValueAt(baris, 1));
            updTem.txteNama.setText(nama);

            String jarak = String.valueOf(tblAlternatif.getValueAt(baris, 2));
            updTem.txteHarga.setText(jarak);

            String kepadatan = String.valueOf(tblAlternatif.getValueAt(baris, 3));
            updTem.txteIsi.setText(kepadatan);

            String harga = String.valueOf(tblAlternatif.getValueAt(baris, 4));
            updTem.txteProtein.setText(harga);

            String aksesibilitas = String.valueOf(tblAlternatif.getValueAt(baris, 5));
            updTem.txteGula.setText(aksesibilitas);

            String luas = String.valueOf(tblAlternatif.getValueAt(baris, 6));
            updTem.txteKalori.setText(luas);

            String info = String.valueOf(tblAlternatif.getValueAt(baris, 7));
            updTem.txteInfo.setText(info);

            updTem.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu");
        }
    }


    private void hapusAlt(int barisDel) {
        if (barisDel >= 0) {
//            int id_Del = (int) tblAlternatif.getValueAt(barisDel, 0);
            String nama = (String) tblAlternatif.getValueAt(barisDel, 1);
            try {
                Connection c = Koneksi.konekKeDB();
                Statement st = c.createStatement();
                String sql = "DELETE FROM tempat_usaha WHERE nama_tempat = '" + nama + "';";
                int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin Untuk Menghapus Data?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (konfirmasi == JOptionPane.YES_OPTION) {
                    st.executeUpdate(sql);
                    loadAlternatif();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                }

            } catch (Exception e) {
                System.err.println(e.getMessage());
            }
        } else {
            JOptionPane.showMessageDialog(this, "Silahkan Pilih Data Terlebih Dahulu!");
        }
    }

    private void hasilSPK() {
        Object[] header = {"NO", "ALTERNATIF", "BOBOT"};
        Object[][] data = null;
        DefaultTableModel model = new DefaultTableModel(data, header);
        hasilPembobotan.setModel(model);

        int nomor = 0;
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            model.getDataVector().removeAllElements();
            String sql = "SELECT * FROM pemilihan ORDER BY hasil DESC";
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                int id = rs.getInt("id");
                String nama = rs.getString("nama");
                double hasil = rs.getDouble("hasil");

                nomor++;
                Object[] d = {nomor, nama, hasil};
                model.addRow(d);
            }
            c.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }


    private void TruncateTbl(String table) {
        try {
            Connection c = Koneksi.konekKeDB();
            Statement st = c.createStatement();
            String sql = "TRUNCATE TABLE " + table + ";";
            st.executeUpdate(sql);
            c.close();
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
    }

}
